--1
SELECT  DECODE(C.COUNTRY, NULL, 'SUMMARY-TOTAL', C.COUNTRY) VISITED_COUNTRY,
          CASE C.COUNTRY
                    WHEN C.COUNTRY THEN DECODE(C.NAME, NULL, 'SUMMARY-COUNTRY', C.NAME ) 
                    ELSE NULL 
          END CITY, 
          CASE C.NAME
                    WHEN C.NAME THEN DECODE(A.NAME, NULL, 'SUMMARY-CITY', A.NAME) 
                    ELSE NULL
          END TYPE, 
          SUM(V.NUMBER_OF_VISITORS) VISITORS,  
          '$' ||' '||SUM(V.PROFIT) PROFIT
FROM CITY C JOIN VISIT V ON C.ID_CITY=V.ID_CITY 
          JOIN ACCOMMODATIONTYPE A ON V.ID_TYPE=A.ID_TYPE
GROUP BY  ROLLUP(C.COUNTRY,C.NAME, A.NAME)
ORDER BY 1,2,3;


--2
SELECT C.COUNTRY VISITED_COUNTRY, T.YEAR, T.MONTH, 
           SUM(V.NUMBER_OF_VISITORS) VISITORS,
           ROUND(AVG(SUM(NUMBER_OF_VISITORS)) 
           OVER (PARTITION BY C.COUNTRY ORDER BY  C.COUNTRY  
           ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING),2) CENTRAL
FROM CITY C JOIN VISIT V ON C.ID_CITY=V.ID_CITY 
          JOIN TIME T ON V.ID_TIME=T.ID_TIME
WHERE UPPER(C.CONTINENT) = 'SOUTH AMERICA' 
GROUP BY C.COUNTRY, T.YEAR, T.MONTH
ORDER BY 1,2;


--3
SELECT DECODE(A.NAME, NULL, 'SUMMARY', A.NAME), T.YEAR, T.MONTH, 
          ' $'||' '||ROUND(SUM(V.PROFIT),1) ZYSK,
          ' $'||' '||ROUND(SUM(SUM(PROFIT)) OVER (PARTITION BY A.NAME ORDER BY T.YEAR
          ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),1) SKUMULOWANY,
          ROUND(RATIO_TO_REPORT(SUM(V.PROFIT)) OVER (PARTITION BY A.NAME )*100,1) UDZIAL
FROM AGE A JOIN VISIT V ON A.ID_AGE=V.ID_AGE 
          JOIN TIME T ON V.ID_TIME=T.ID_TIME
GROUP BY GROUPING SETS ((A.NAME, T.YEAR, T.MONTH),()) ;


--4
SELECT C.COUNTRY, C.NAME,
        DENSE_RANK() OVER (PARTITION BY C.COUNTRY ORDER BY SUM(V.NUMBER_OF_VISITORS) DESC NULLS LAST) RANK1,
        DENSE_RANK() OVER (PARTITION BY C.COUNTRY ORDER BY SUM(V.PROFIT)) RANK2
FROM CITY C LEFT JOIN VISIT V ON C.ID_CITY=V.ID_CITY
WHERE UPPER(C.CONTINENT) = 'SOUTH AMERICA'
GROUP BY C.COUNTRY,C.NAME
ORDER BY C.COUNTRY;


--5
SELECT *
FROM(
          SELECT DECODE(C.COUNTRY,NULL,' ---TOTAL---',C.COUNTRY) AS COUNTRY , 
                DECODE(A.NAME,NULL,'TOTAL',A.NAME) AS NAME, SUM(V.NUMBER_OF_VISITS) LICZBA_ODWIEDZIN
          FROM CITY C JOIN VISIT V ON C.ID_CITY=V.ID_CITY 
                    JOIN AGE A ON A.ID_AGE=V.ID_AGE
          WHERE UPPER(C.CONTINENT) ='EUROPE'
          GROUP BY CUBE (C.COUNTRY, A.NAME)
) PIVOT(SUM(LICZBA_ODWIEDZIN) FOR NAME IN('child','teenager','young adult', 'adult', 'middle age','senior','TOTAL'))
ORDER BY 1 DESC NULLS LAST;







